


// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 11 Jul 2014 12:07:23 GMT

using System.Reflection;

[assembly: AssemblyVersion    ("1.0.17411.0")]
[assembly: AssemblyFileVersion("1.0.17411.1207")]
