


// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Wed, 16 Jul 2014 22:14:53 GMT

using System.Reflection;

[assembly: AssemblyVersion    ("2.0.17416.0")]
[assembly: AssemblyFileVersion("2.0.17416.2214")]
